spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contacts
    username: root
    password: root
    driverClassName: com.mysql.jdb.Driver
  jpa:
    hibernate.ddl.auto: update
    generate-ddl: true
    show-sql: true

